# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XwUkCq0Mox9RJSRBWDv5NUspN8Ru1ZDZ
"""

from google.colab import drive
drive.mount('/content/drive')

path="/content/TASK 2 UNEMPLoyment in india.csv"

"""TASK 2 UNEMPLOYMENT ANALYSIS WITH PYTHON"""

import pandas as pd
df=pd.read_csv("/content/TASK 2 UNEMPLoyment in india.csv")
df.head()

df.info()

df.isnull().sum()

df=df.dropna()

df.isnull().sum()

df.describe()

print(df.columns)

df.columns=df.columns.str.strip()

"""DISTRIBUTION OF UNEMPLOYMENT RATE"""

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
sns.histplot(df['Estimated Unemployment Rate (%)'],
             bins=20,
             kde=True)

plt.title('Distribution of Unemployment Rate')
plt.show()

"""TOP 10 STATES WITH HIGHEST UNEMPLOYMENT"""

top_states = df.groupby('Region')['Estimated Unemployment Rate (%)'].mean()

top_states = top_states.sort_values(ascending=False).head(10)

plt.figure(figsize=(10,5))
top_states.plot(kind='bar')

plt.title('Top 10 States by Average Unemployment Rate')
plt.ylabel('Unemployment Rate (%)')
plt.show()

"""URBAN VS RURAL UNEMPLOYMENT"""

sns.boxplot(
    x='Area',
    y='Estimated Unemployment Rate (%)',
    data=df
)

plt.title('Urban vs Rural Unemployment')
plt.show()

"""IMPACT OF COVID-19 ON UNEMPLOYMENT"""

plt.figure(figsize=(12,5))

df.groupby('Date')['Estimated Unemployment Rate (%)'].mean().plot()

plt.title('Impact of COVID-19 on Unemployment')
plt.ylabel('Unemployment Rate (%)')
plt.xlabel('Date')

plt.show()

"""CONCLUSION

The analysis showed that unemployment rates varied across different states. Some states such as Tripura and Haryana had higher average unemployment rates compared to others.

The comparison between urban and rural areas showed that urban areas generally had higher unemployment rates than rural areas.
The COVID-19 trend analysis revealed a sharp increase in unemployment during April and May 2020 due to lockdown restrictions. After that period, unemployment gradually decreased as economic activities resumed. Had higher unemployment rates than rural areas.
The COVID-19 trend analysis revealed a sharp increase in unemployment during April and May 2020 due to lockdown restrictions. After that period, unemployment gradually decreased as economic activities resumed.
Overall, this project helped in understanding unemployment patterns, the impact of COVID-19, and regional differences in employment across India using data analysis and visualization techniques.
"""